# Generated by Django 4.2.5 on 2023-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='readBy',
            field=models.ManyToManyField(blank=True, related_name='readBy', to='user.user', verbose_name='Read By'),
        ),
    ]
