# Generated by Django 4.1 on 2023-10-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_message_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date'], 'verbose_name_plural': 'Messages'},
        ),
    ]
