# Generated by Django 4.1 on 2023-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pkeSentBy',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='pke'),
        ),
    ]
