# Generated by Django 4.2.6 on 2023-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Urgent')], verbose_name='Priority'),
        ),
    ]
