# Generated by Django 4.1 on 2023-11-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_message_pkereceiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pkeReceiver',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='pke Receiver'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pkeSentBy',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='pke Sent By'),
        ),
    ]
