# Generated by Django 4.2.5 on 2023-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='message', to='group.message', verbose_name='message'),
        ),
    ]
