# Generated by Django 4.2.5 on 2023-10-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
    ]
