# Generated by Django 4.2.6 on 2023-10-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_lastactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], verbose_name='status'),
        ),
    ]
