# Generated by Django 4.2.6 on 2023-10-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=128, unique=True, verbose_name='Telefone'),
        ),
    ]
